# GENERATED BY GEMINI 3 PRO

import os
from PIL import Image

# --- CONFIGURATION ---
INPUT_IMAGE  = "/Users/alyssabernard/Documents/GitHub/fl-dendro/mr-cnn_testing/IMG_6001_crop.jpg" # Your 3392x116 image
OUTPUT_FOLDER = "/Users/alyssabernard/Documents/GitHub/fl-dendro/mr-cnn_testing/crop_tiles"
TILE_SIZE = 1024
OVERLAP = 200 # Increased overlap to ensure the AI sees enough context

if not os.path.exists(OUTPUT_FOLDER):
    os.makedirs(OUTPUT_FOLDER)

def tile_thin_strip():
    img = Image.open(INPUT_IMAGE).convert("RGB")
    width, height = img.size
    print(f"Input dimensions: {width}w x {height}h")

    # We only need to loop across the width (left to right)
    # because the height (116px) already fits inside the 1024px tile.
    count = 0
    left = 0
    
    while left < width:
        # Define the box. 
        # We keep 'top' at 0 and 'bottom' at the full height of the image.
        # Mask R-CNN will pad the rest of the 1024px height with black pixels.
        right = left + TILE_SIZE
        
        # If we are at the end of the image, adjust 'left' so we don't go out of bounds
        if right > width:
            right = width
            left = max(0, width - TILE_SIZE)
        
        box = (left, 0, right, height)
        tile = img.crop(box)
        
        # Save tile
        tile_name = f"tile_x{left}.png"
        tile.save(os.path.join(OUTPUT_FOLDER, tile_name))
        count += 1
        
        # If we reached the end, break the loop
        if right == width:
            break
            
        left += (TILE_SIZE - OVERLAP)
            
    print(f"Done! Created {count} horizontal tiles.")

if __name__ == "__main__":
    tile_thin_strip()